#!/usr/bin/env python3
"""
Generate real camera-style JPEG/PNG inputs for the real-image verifier.

Each generated file embeds:
  * EXIF (Make, Model, Software, DateTime, ImageDescription)
  * An actual ICC color profile (sRGB) — generated by Pillow's ImageCms at test time
  * A JPEG COM segment with a privacy-relevant string
  * IPTC and XMP, where Pillow supports them

The earlier version of this script passed `exif=` and `comment=` to `img.save`
but did NOT pass an `icc_profile=`. That meant all three strip profiles produced
identical output (since they differ only on ICC handling) and the verifier could
not distinguish them. This version injects a real sRGB profile so Privacy/
AllMetadata drop it and Minimal keeps it.
"""

import io
import os
import sys
import tempfile

from PIL import Image, ImageCms
from PIL.ExifTags import Base as ExifBase


def build_real_jpeg_with_full_metadata(width: int = 64, height: int = 64) -> bytes:
    """JPEG with EXIF, ICC, COM, XMP — exercises every strip-profile difference."""
    exif = Image.Exif()
    exif[ExifBase.Make] = "TestCamCo"
    exif[ExifBase.Model] = "TC-100"
    exif[ExifBase.Software] = "TestSoft 2.0"
    exif[ExifBase.DateTimeOriginal] = "2024:06:15 10:30:00"
    exif[ExifBase.ImageDescription] = "Test photo with metadata"

    img = Image.new("RGB", (width, height), (255, 128, 64))
    # Add some pixel variation so the entropy-coded scan has real data
    # (real camera photos don't have constant-color regions; an all-one-color
    # image compresses to almost nothing and skips 0xFF00 byte-stuffing).
    pixels = img.load()
    for y in range(height):
        for x in range(width):
            pixels[x, y] = ((x * 7) % 256, (y * 11) % 256, ((x + y) * 5) % 256)

    # Build a real sRGB ICC profile. Pillow's ImageCms ships the sRGB profile
    # as a built-in; createProfile returns a working CmsProfile we can serialize.
    srgb_profile = ImageCms.createProfile("sRGB")
    icc_bytes = ImageCms.ImageCmsProfile(srgb_profile).tobytes()

    xmp_packet = (
        b"http://ns.adobe.com/xap/1.0/\x00"
        b"<?xpacket begin='' id=''?>"
        b"<x:xmpmeta xmlns:x='adobe:ns:meta/'>"
        b"<rdf:RDF xmlns:rdf='http://www.w3.org/1999/02/22-rdf-syntax-ns#'>"
        b"<rdf:Description xmp:CreatorTool='Adobe Lightroom 13' "
        b"xmp:CreateDate='2024-06-15T10:30:00Z'/>"
        b"</rdf:RDF></x:xmpmeta><?xpacket end='w'?>"
    )

    buf = io.BytesIO()
    img.save(
        buf,
        format="JPEG",
        quality=90,
        exif=exif.tobytes(),
        icc_profile=icc_bytes,
        comment="Photo by Test User on DESKTOP-JDOE",
        xmp=xmp_packet,
    )
    return buf.getvalue()


def write_file(path: str, data: bytes) -> None:
    with open(path, "wb") as f:
        f.write(data)
    print(f"  Wrote {os.path.basename(path)} ({len(data)} bytes)")


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: gen_test_jpeg.py <output-dir> [width] [height]", file=sys.stderr)
        return 2

    out_dir = sys.argv[1]
    os.makedirs(out_dir, exist_ok=True)

    width = int(sys.argv[2]) if len(sys.argv) > 2 else 64
    height = int(sys.argv[3]) if len(sys.argv) > 3 else 64

    print(f"Generating real camera-style JPEG with EXIF + ICC + COM + XMP ({width}x{height})")
    jpeg_full = build_real_jpeg_with_full_metadata(width, height)
    write_file(os.path.join(out_dir, "real_full.jpg"), jpeg_full)

    print("Generating bare JPEG (no metadata — regression for the '0/1 file' case)")
    img = Image.new("RGB", (32, 32), (10, 20, 30))
    bare_buf = io.BytesIO()
    img.save(bare_buf, format="JPEG", quality=85)
    write_file(os.path.join(out_dir, "real_bare.jpg"), bare_buf.getvalue())

    return 0


if __name__ == "__main__":
    sys.exit(main())
